//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refaccionaria_DB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RefaccionariaEntities1 : DbContext
    {
        public RefaccionariaEntities1()
            : base("name=RefaccionariaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesorio> Accesorio { get; set; }
        public virtual DbSet<Asentamiento> Asentamiento { get; set; }
        public virtual DbSet<AutoParte> AutoParte { get; set; }
        public virtual DbSet<AutoparteSucursal> AutoparteSucursal { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<ClienteCompra> ClienteCompra { get; set; }
        public virtual DbSet<ClienteProducto> ClienteProducto { get; set; }
        public virtual DbSet<ClienteSucursal> ClienteSucursal { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EmpleadoProducto> EmpleadoProducto { get; set; }
        public virtual DbSet<EquipoComputo> EquipoComputo { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Moviliario> Moviliario { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProductoCompra> ProductoCompra { get; set; }
        public virtual DbSet<ProductoVenta> ProductoVenta { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Publicidad> Publicidad { get; set; }
        public virtual DbSet<Quimicos> Quimicos { get; set; }
        public virtual DbSet<QuimicosSucursal> QuimicosSucursal { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<SucursalAccesorio> SucursalAccesorio { get; set; }
        public virtual DbSet<SucursalEmpleado> SucursalEmpleado { get; set; }
        public virtual DbSet<SucursalEquipoComputo> SucursalEquipoComputo { get; set; }
        public virtual DbSet<SucursalEstado> SucursalEstado { get; set; }
        public virtual DbSet<SucursalMoviliario> SucursalMoviliario { get; set; }
        public virtual DbSet<SucursalProveedor> SucursalProveedor { get; set; }
        public virtual DbSet<SucursalPublicidad> SucursalPublicidad { get; set; }
        public virtual DbSet<TipoAsentamiento> TipoAsentamiento { get; set; }
        public virtual DbSet<TipoAsentamientoZona> TipoAsentamientoZona { get; set; }
        public virtual DbSet<TipoAutoparte> TipoAutoparte { get; set; }
        public virtual DbSet<TipoEmpleado> TipoEmpleado { get; set; }
        public virtual DbSet<TipoProveedor> TipoProveedor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentaEmpleado> VentaEmpleado { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
    }
}
